### ISSUE TITLE
Fix memory issues in firefox

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye-js#1066]
Have been told there are still memory leaks in firefox. This is an issue to investigate.

Please supply details / repros here if you've experienced this issue.

**Comment by jeswr** [comment]
Note that [memlab does not currently support firefox](https://github.com/facebook/memlab/issues/32#issuecomment-1255298496) which would explain why this is not caught by our CI.

**Comment by smeckler** [comment]
Thank you for looking into this issue, Jesse. 

For testing, you can simply use the example from `examples/prebuilt` and build a loop around it. Here is a little code snippet: https://pastebin.com/bTgGbVJ6

I tested on Firefox 115.10.0esr (32-bit) with the latest and older eye-js CDN scripts.
On my machine, Firefox consistently runs into memory problems after 6 iterations of the Socrates example. A delay between executions (e.g. 10s) does not change anything. If I use a longer data string, the memory limit is reached after 4-5 iterations.

Stack trace of the memory error:
````
Uncaught (in promise) RuntimeError: Aborted(out of memory). Build with -sASSERTIONS for more info.
    abort https://eyereasoner.github.io/eye-js/latest/index.js:2
    SWIPL https://eyereasoner.github.io/eye-js/latest/index.js:2
    promise callback*instantiateArrayBuffer https://eyereasoner.github.io/eye-js/latest/index.js:2
    instantiateAsync https://eyereasoner.github.io/eye-js/latest/index.js:2
    createWasm https://eyereasoner.github.io/eye-js/latest/index.js:2
    SWIPL https://eyereasoner.github.io/eye-js/latest/index.js:2
    N https://eyereasoner.github.io/eye-js/latest/index.js:2
    F https://eyereasoner.github.io/eye-js/latest/index.js:2
    n3reasoner https://eyereasoner.github.io/eye-js/latest/index.js:2
    <anonymous> file:///C:/Users/mkl/Downloads/index.html:22

**Comment by jeswr** [comment]
Notes to self:
 - Have been able to repro, happens after about ~250 iterations in the loop for me.
 - The same modified iteration script runs sucessfully in chrome, and taking snapshots of the heap does not show any increases in memory.
 
 Now investigating the cause.

**Comment by jeswr** [comment]
The cause is somewhere in `swipl-wasm` or it's upstream dependencies, and the memory usage seems to come from *instantiating* SWIPL. This has been identified by making `__test_utils/browser.html` be

```html
<!DOCTYPE html>
<html>
  <body>
    <textarea id="data" rows="10" cols="75">
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix : <http://example.org/socrates#>.

:Socrates a :Human.
:Human rdfs:subClassOf :Mortal.

{?A rdfs:subClassOf ?B. ?S a ?A} => {?S a ?B}.</textarea
    >
    <button id="execute">Execute</button>
    <button id="clear">Clear</button>
    <div id="result"></div>
  </body>
  <script src="/index.js"></script>
  <script>
    document.getElementById('execute').addEventListener("click", async () => {
      
      try {
        for (let i = 0; i < 1000; i += 1) {
          if (i % 50 === 0) {
            console.log(i)
          }
          await eyereasoner.SWIPL();
        }
  
        
      } catch (e) {
        console.error(e)
      }
    });

    document.getElementById('clear').addEventListener("click", async () => {
      
      document.getElementById("result").innerHTML = '';

    });
  </script>
</html>

```

and `lib/index.ts` be
```ts
/* istanbul ignore file */
export * from './query';
export * from './transformers';
export { default as EYE_PVM } from './eye';
export { default as SWIPL } from 'swipl-wasm/dist/swipl/swipl-bundle-no-data';
```

**Comment by jeswr** [comment]
Progress with this issue can now be tracked in https://github.com/emscripten-core/emscripten/issues/21892. I will open a separate issue on this repo to add a test.

**Comment by jeswr** [comment]
This turned out to be an issue in Firefox - see https://bugzilla.mozilla.org/show_bug.cgi?id=1895309.
