### ISSUE TITLE
Reasoner option 'undefined' is not working as aspected

### ISSUE THREAD

**Issue by phochste** [eyereasoner/eye-js#1113]
To run RDF Surfaces in the eye-js I require no extra `--pass*` options for the eye reasoner.

```
const result = await n3reasoner(data, undefined, {
  output: undefined,
  bnodeRelabeling: false,
  outputType: 'string'
});
```

Does not work as expected due to a missing break in https://github.com/eyereasoner/eye-js/blob/main/lib/transformers.ts#L96

**Comment by phochste** [comment]
Or if the default is intended. I would like to have an extra option added (i don't know a good name `none` maybe) that has the effect of not adding pass options.

**Comment by jeswr** [comment]
This is the intended behavior, so an extra option would be better @phochste. `skip` or `none` is fine. PR is welcome :)
