### ISSUE TITLE
Any chance you can create a compiled version in your repo?

### ISSUE THREAD

**Issue by Skreen5hot** [eyereasoner/eye-js#1410]
I am currently trying to use eye-js in my project but am encountering difficulties with the build process. Specifically, I am unable to compile the TypeScript files into JavaScript due to various setup issues. As I am unable to proceed with the compilation myself, I would like to request a precompiled version of eye-js in JavaScript so that I can continue with my integration.

Could you please provide a compiled .js version of the library, or alternatively, direct me to any precompiled releases that may already exist in the repository?

**Comment by jeswr** [comment]
Hi!

You can l the recompiled version in several places:
 - https://eyereasoner.github.io/eye-js/latest/index.js (see browser builds in the readme)
 - On the pages branch (which is where the above browser build is served from)
 - On NPM

No user of this package should be building it themselves.

**Comment by jeswr** [comment]
Hi!

You can l the recompiled version in several places:
 - https://eyereasoner.github.io/eye-js/latest/index.js (see browser builds in the readme). Also see the example app in this repo to see how you can import this into your app using the script tag.
 - On the pages branch (which is where the above browser build is served from)
 - On NPM

No user of this package should be building it themselves.

**Comment by jeswr** [comment]
Closing this issue as I assume your problem is resolved - feel free to reopen if you encounter any more issues.

Feel free to re-open if you have any more questions / issues. PRs are welcome for helping to clarify the docs :)
