### ISSUE TITLE
Use `pvm` file for faster startup

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye-js#20]

**Comment by josd** [comment]
The image is currently made with https://github.com/eyereasoner/eye/blob/master/install.sh line https://github.com/eyereasoner/eye/blob/master/install.sh#L34
The image is currently called in https://github.com/eyereasoner/eye/blob/master/eye.sh

**Comment by jeswr** [comment]
What I am struggling with is trying to work out how to generate the `.pvm` file in the WASM version of SWIPL since those arguments are provided when you intialise the module. That is, at what point can I call `Module.fs.writeFile('eye.pl', ...)` in

```
import { SWIPLModule } from 'swipl-wasm/dist/common';
import { queryOnce, runQuery, SWIPL, writeEye } from '..';

(async () => {
  const Module : SWIPLModule= await SWIPL({ print: (s: string) => {
    console.log(s);
  }, arguments: ['-f', 'eye.pl', '-g', 'main', '--', '--version'] } as EmscriptenModule);

})();

```

**Comment by jeswr** [comment]
I've gotten as far as https://github.com/eyereasoner/eye-js/pull/21 - where we can now run `npm i` and the end result is that `eye.pvm` gets built and then we generate the file `lib/eye.pvm.ts`.

The problem that I am now encountering is that I don't really know what do *do* with this; in the example you give you're calling it from the command line without SWIPL being involved at all now - but with the WASM version we can't really do that; so how would I run the pvm file using the current tooling?

**Comment by jeswr** [comment]
I've now tried

```ts
(async () => {
  const Module: SWIPLModule = await SWIPL({
    arguments: ['-x', './eye.pvm', '--', '"$@"'],
    preRun: (module: SWIPLModule) => {
      module.FS.writeFile('eye.pvm', fs.readFileSync(path.join(__dirname, '..', 'eye', 'eye.pvm')).toString());
    },
    print: console.log,
    printError: console.log
  });
})();
```

but it errors out with

```bash
[FATAL ERROR: at Fri Jan  6 10:51:30 2023
        Could not open resource database "./eye.pvm": Not a tty]
Aborted()
```

**Comment by JanWielemaker** [comment]
I don't know.    Seems it cannot open eye.pvm and the reported errno is bogus.

**Comment by jeswr** [comment]
>  Seems it cannot open eye.pvm and the reported errno is bogus.

As in failing to parse it? It is definitely finding the file because if I remove [the step adding `eye.pvm`](https://github.com/eyereasoner/eye-js/blob/9b088f74636a3dbbb322813cd04b659e4d6f1a33/scripts/run-pvm.ts#L10-L12) we get the (sensible) error

```
[FATAL ERROR: at Sat Jan  7 17:23:34 2023
        Could not open resource database "eye.pvm": No such file or directory]
Aborted()
```

**Comment by JanWielemaker** [comment]
Ok.   Note that the eye.pvm is a zip file.  If it is opened but unusable as resource file it is probably an invalid zip file according to the embedded minizip library.

**Comment by jeswr** [comment]
Ah - thanks for clarifying (in particular the fact that it is a zip)! I've fixed it; the problem was the `.toString()` conversion in    `module.FS.writeFile('eye.pvm', fs.readFileSync(path.join(__dirname, '..', 'eye', 'eye.pvm')).toString())`.

Now I just need to figure out how to save the PVM as something that I can inline; without massively blowing up the size by just saving the elements of the buffer.

**Comment by josd** [comment]
`.pvm` is a swipl quick load format which we use to make the generic reasoning engine `eye.pvm` but also and esp. for specialized reasoning engines preloaded with large amounts of so called static `.ttl` data and `.n3` rules.

**Comment by josd** [comment]
Thank you so much @jeswr and @JanWielemaker, the eye initialization is now 5 times faster!
