### ISSUE TITLE
possible serialization issue

### ISSUE THREAD

**Issue by giacomociti** [eyereasoner/eye-js#208]
the following rule works fine [in the browser](https://eyereasoner.github.io/eye-js/example/) but gives no result using node.
```
@prefix : <http://ex.org/> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .

:a :b :c, :d .

{
    (?x
     {:a :b ?x }
     ?list) log:collectAllIn _:x .
}
=>
{
  :result :is ?list
} .
```
Apparently, its serialization in the temporary file is missing `{:a :b ?x }`

```
<http://ex.org/a> <http://ex.org/b> <http://ex.org/c> . 
<http://ex.org/a> <http://ex.org/b> <http://ex.org/d> . 

{
 _:n3-1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> ?x . 
 _:n3-1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:n3-3 . 
 _:n3-1 <http://www.w3.org/2000/10/swap/log#collectAllIn> _:n3-0.x . 
 _:n3-3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> ?list . 
 _:n3-3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> . 
 } => {<http://ex.org/result> <http://ex.org/is> ?list . } . 
```

**Comment by jeswr** [comment]
The fix should be easy - we just need the same logic as https://github.com/eyereasoner/eye-js/blob/3b2e074c8ade3ad747e460119ff0121dae6a25f3/lib/n3Writer.temp.ts#L26-L28 in the `_encodePredicate` method in `lib/n3Writer.temp.ts`. Could you make a PR with the changes?

**Comment by giacomociti** [comment]
> > the following rule works fine [in the browser](https://eyereasoner.github.io/eye-js/example/) but gives no result using node.
> 
> I'm assuming that if you use strings in node it works fine but if you give RDF/JS input and request string output then you get this problem?

exactly

**Comment by giacomociti** [comment]
https://github.com/rdfjs/N3.js/issues/342
