### ISSUE TITLE
should we remove the `eye.pl` APIs entirely

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye-js#25]
In https://github.com/eyereasoner/eye-js/pull/21 I have marked all APIs that instantiate eye via `eye.pl` as deprecated; favoring initialization with `eye.pvm`. I have also updated the docs accordingly.

I would like to know if there is any value in keeping these APIs or whether we can just remove them entirely; and make this library easier to maintain.

// cc @josd

**Comment by josd** [comment]
Not sure but I would be inclined to remove those APIs.
