### ISSUE TITLE
flaky workflows

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye-js#26]
Since https://github.com/eyereasoner/eye-js/commit/0375315460365ab14afbdd75e5377148d86800c0 our workflows have become quite flakey because one of the GitHub urls we are requesting seems to be 404ing at a high rate. If this keeps happening we may need to change the method we use to retrieve the `eye.pl` asset.

**Comment by josd** [comment]
Hmm... here it works fine
```
$ repeat 100 curl -I https://raw.githubusercontent.com/eyereasoner/eye/v2.0.1/eye.pl 2>&1 | grep HTTP/2\ 200 | wc -l
100
```

**Comment by josd** [comment]
where
```
$ cat /usr/local/bin/repeat
#!/bin/bash
n=$1
shift
seq $n | xargs -n1 -I {} "$@"
```

**Comment by jeswr** [comment]
Good to know - in that case I suspect github might be applying some kind of rate limiting within the workflows

**Comment by josd** [comment]
Indeed and just finished a 1000 repeat without trouble.

**Comment by jeswr** [comment]
Largely resolved now that all parts of the CI workflow share the same fetch data
