### ISSUE TITLE
Question: What is in a `pvm`?

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye-js#28]
I'm wondering how much information is contained in the `pvm` image; in particular has it pre-loaded many/any of the SWIPL modules (such as those listed in https://github.com/SWI-Prolog/swipl-devel/blob/master/src/wasm/exports.json) which would allow us to create a custom minified build of SWIPL?

**Comment by josd** [comment]
In [eye.pl](https://github.com/eyereasoner/eye/blob/master/eye.pl#L8) there are 13 `use_module/1` directives and I assume they are in the `pvm` file. So I would think that is all we need and if not we can have additional `use_module/1` directives.

**Comment by josd** [comment]
Yes, I did an explicit test with `:- set_prolog_flag(autoload, false).` and the image was running fine for all our tests. So all needed modules are in the `pvm` file.
