### ISSUE TITLE
Feature Request: make built in log:uuid work

### ISSUE THREAD

**Issue by woutslabbinck** [eyereasoner/eye-js#290]
With eye, I can use the `log:uuid` build in to create a uuid string.

E.g.

```n3
@prefix : <urn:example:> .
@prefix log: <http://www.w3.org/2000/10/swap/log#> .
@prefix string: <http://www.w3.org/2000/10/swap/string#> .

{
    # Generates UUID Y using IRI X
    #    X an iri
    #    Y a string

    :test log:uuid ?Y .
    ( "urn:uuid:" ?Y ) string:concatenation ?YT .
        ?Z log:uri ?YT .
}
=> 
{ 
    :Result :uuid ?Z .
} .
```

Will result in
```turtle
@prefix : <urn:example:> .
@prefix log: <http://www.w3.org/2000/10/swap/log#>.
@prefix string: <http://www.w3.org/2000/10/swap/string#>.

:Result :uuid <urn:uuid:e85be12a-ea7b-11ed-ad97-8f98520311e0>.
```

However, when I execute the following code with the `eyereasoner`, I get no uuid uri:

```javascript
import { n3reasoner,SwiplEye,queryOnce  } from 'eyereasoner';

async function main() {
    const queryString = `
    @prefix : <http://example.org/socrates#>.
    @prefix log: <http://www.w3.org/2000/10/swap/log#> .
    @prefix string: <http://www.w3.org/2000/10/swap/string#> .
    {:Socrates a ?WHAT} => {:Socrates a ?WHAT}.

{
    
        :test log:uuid ?Y .
        ( "urn:uuid:" ?Y ) string:concatenation ?YT .
         ?Z log:uri ?YT .
    }
    => 
    { 
        :Result :uuid ?Z .
    } .
`;

    const dataString = `
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix : <http://example.org/socrates#>.

:Socrates a :Human.
:Human rdfs:subClassOf :Mortal.

{?A rdfs:subClassOf ?B. ?S a ?A} => {?S a ?B}.
`;

    // The result of the query (as a string)

        // Instantiate a new SWIPL module and log any results it produces to the console
        const Module = await SwiplEye({ print: (str: string) => { console.log(str) }, arguments: ['-q'] });
      
        // Load the the strings data and query as files data.n3 and query.n3 into the module
        Module.FS.writeFile('data.n3', dataString);
        Module.FS.writeFile('query.n3', queryString);
      
        // Execute main(['--nope', '--quiet', './data.n3', '--query', './query.n3']).
        queryOnce(Module, 'main', ['--nope', '--quiet', './data.n3', '--query', './query.n3']);
      
    
}
main()
```

So my question is, can the `log:uuid` built-in also be part of the wasm eye reasoner?

**Comment by jeswr** [comment]
I recently (in the last hour) learned that swipl-wasm is not passing a bunch of the swipl tests even though it can.

That is `ctest` mentioned [here](https://swi-prolog.discourse.group/t/wasm-updates/6516) has a bunch of failing tests for the version of swipl used in this library; even though we should be able to get all tests to pass.

I'll ask you to test all this again after I get that working :)

**Comment by jeswr** [comment]
@woutslabbinck would you be able to create a PR here with some test cases for `log:uuid` so that we can avoid regressions once support is added.

These test cases should be added [here](https://github.com/eyereasoner/eye-js/blob/87147784aa1c91f1d42092d703ff554c1a7c5a34/__test_utils__/util.ts#L86)

**Comment by woutslabbinck** [comment]
Sure!
Will you let me know then when this is implemented so I can create a PR?

**Comment by jeswr** [comment]
@josd does this mean that eye no longer requires the uuid package at all?

If so I will remove this proposed test upstream https://github.com/SWI-Prolog/npm-swipl-wasm/blob/master/tests/node.js#L32.

**Comment by josd** [comment]
Yes @jeswr you can remove the uuid package dependency.
