### ISSUE TITLE
Using eye-js in the browser

### ISSUE THREAD

**Issue by william-vw** [eyereasoner/eye-js#36]
Great library!! Could you please give an example of how to use eye-js in the browser, if possible?

**Comment by josd** [comment]
For the moment have a look at https://github.com/smessie/SWIPL-WASM-Example
@jeswr could we have it briefly in README.md ?

**Comment by william-vw** [comment]
Thanks @josd 
Yes, it would be great if a bare-bones example could be given (i.e., using "vanilla" JS) to use eye-js in the browser.

**Comment by jeswr** [comment]
There is now an example of browser usage via we pack in the examples folder.

I will also try and create a bundled version of this package that is hosted on GitHub pages so leave this open until I complete that task.

**Comment by jeswr** [comment]
I now also have bundles being created in github pages - so we can now create a website using eyereasoner in 35 lines of html https://github.com/eyereasoner/eye-js/blob/main/examples/prebuilt/index.html :)

**Comment by josd** [comment]
Thank you very much @jeswr and the example https://eyereasoner.github.io/eye-js/example/ runs nicely!

**Comment by jeswr** [comment]
> Just to point out that https://eyereasoner.github.io/eye-js/latest/index.js exposes the global eyereasoner variable for use within the browser, but https://eyereasoner.github.io/eye-js/2/3/8/index.js does not.

Good point - I indeed did a bug fix for that in 2.3.9; but I should not have been using the broken 2.3.8 in the docs because of that. I've made https://github.com/eyereasoner/eye-js/pull/58 to fix the docs.

**Comment by jeswr** [comment]
> Also, and just being difficult now - would it be possible to generate a separate dist file with an export statement in case people want to load eye-js dynamically (using import) within the browser? (It's easy enough to add this by oneself so not that important!)

Are the exports on unpkg (these are automatically generated from the [NPM](https://www.npmjs.com/package/eyereasoner) distribution) sufficient (e.g. https://unpkg.com/eyereasoner@2.3.14/dist/index.js) or did you want it all bundled in a single file that can be dynamically imported?

**Comment by jeswr** [comment]
Happy to accept a PR if you know what you want added :)

**Comment by william-vw** [comment]
@jeswr 
> Are the exports on unpkg (these are automatically generated from the [NPM](https://www.npmjs.com/package/eyereasoner) distribution) sufficient (e.g. https://unpkg.com/eyereasoner@2.3.14/dist/index.js) or did you want it all bundled in a single file that can be dynamically imported?

The latter (single bundle) would be quite useful - the same as the [current bundles](https://eyereasoner.github.io/eye-js/latest/index.js), with a simple "export" added at the start of the file, worked for me:
```
export var eyereasoner; ...
```
Re the PR, I'm unsure how to adapt your current build process :-)

**Comment by william-vw** [comment]
@jeswr FYI, this code sample doesn't work in the browser since the eyereasoner variable is not being exported in https://eyereasoner.github.io/eye-js/2/latest/index.js - also it is relying on a typescript static type (`str:String`) in the print function.

**Comment by jeswr** [comment]
Code example is now fixed - note that you want to be using the link https://eyereasoner.github.io/eye-js/2/latest/dynamic-import.js rather than https://eyereasoner.github.io/eye-js/2/latest/index.js

**Comment by william-vw** [comment]
Great, thanks!
