### ISSUE TITLE
broken links and fragments in https://github.com/eyereasoner/eye-js

### ISSUE THREAD

**Issue by josd** [eyereasoner/eye-js#41]
error Lines: 1229, 1271 https://github.com/eyereasoner/eye-js/tree/%7B%7B%20urlEncodedRefName%20%7D%7D
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Line: 2319 https://eyereasoner.github.io/eye-js/example/index.html
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

error Lines: 145, 585, 598, 632, 645, 670, 683, 708, 721, 859, 974, 1067, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2064, 2071, 2198, 2261, 2302, 2315, 2321, 2679, 2680 https://github.com/eyereasoner/eye-js
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://github.com/eyereasoner/eye-js#usage (lines 2046, 2071)
https://github.com/eyereasoner/eye-js#license (lines 2051, 2321)
https://github.com/eyereasoner/eye-js#advanced-usage (lines 2047, 2198)
https://github.com/eyereasoner/eye-js#examples (lines 2050, 2315)
https://github.com/eyereasoner/eye-js#cli-usage (lines 2049, 2302)
https://github.com/eyereasoner/eye-js#eye-js (lines 2045, 2064)
https://github.com/eyereasoner/eye-js#selecting-the-swipl-module (lines 2048, 2261)

**Comment by josd** [comment]
This was tested with https://validator.w3.org/checklink?uri=https%3A%2F%2Fgithub.com%2Feyereasoner%2Feye-js&hide_type=all&depth=&check=Check

**Comment by jeswr** [comment]
This for the report @josd - https://eyereasoner.github.io/eye-js/example/index.html is now fixed; and the fragments are false positives (they work when you click on them - and are generated by github based on the README).

I think https://github.com/eyereasoner/eye-js/tree/%7B%7B%20urlEncodedRefName%20%7D%7D is also a false positive 

```bash
jesse@ranchmorty:~/Documents/github/es/ei/eye-js$ curl https://github.com/eyereasoner/eye-js | grep EncodedRefName
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  <a href="https://github.com/eyereasoner/eye-js/tree/{{ urlEncodedRefName }}" class="SelectMenu-item" role="menuitemradio" rel="nofollow" aria-checked="{{ isCurrent }}" data-index="{{ index }}" >
  <a href="https://github.com/eyereasoner/eye-js/tree/{{ urlEncodedRefName }}" class="SelectMenu-item" role="menuitemradio" rel="nofollow" aria-checked="{{ isCurrent }}" data-index="{{ index }}" >
100  237k    0  237k    0     0   300k      0 --:--:-- --:--:-- --:--:--  300k
```

Closing as I think that covers all the relevant links; let me know if I missed anything.
