### ISSUE TITLE
Multi-query support

### ISSUE THREAD

**Issue by william-vw** [eyereasoner/eye-js#427]
Wondering whether eye-js has multi-query support, i.e., a query-answer loop (@josd had graciously re-added this to the regular eye a while back)?  

I'm aware of the [queryOnce](https://github.com/eyereasoner/eye-js/blob/main/lib/query.ts#L20) method - perhaps it could be as easy as invoking a `multi()` method on the module? :-) (or, perhaps this is wishful thinking and I misinterpreted that method call!)

**Comment by josd** [comment]
A while back `--multi-query` was definitely removed from eye.
One has to do streaming and/or dialogical reasoning on top of eye that is with separate reasoning runs.
